{
 "title": "couchdb-car2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"prometheus-exporter-car2:9984\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "couchdb_httpd_requests{instance=\"prometheus-exporter-car2:9984\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database write operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "couchdb_httpd_database_writes{instance=\"prometheus-exporter-car2:9984\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicator requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "couchdb_replicator_requests{instance=\"prometheus-exporter-car2:9984\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database read operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "couchdb_httpd_database_reads{instance=\"prometheus-exporter-car2:9984\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"prometheus-exporter-car2:9984\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}